---
# Generic remove container role
# Uses a "loop_list" variable to stop multiple containers if needed

- name: Remove VM
  community.general.proxmox_kvm:
    api_user: ansible@pam
    api_password: "{{ api_token_secret }}"
    api_host: 127.0.0.1
    name: "{{ item }}"
    node: pve
    state: absent
  loop: "{{ loop_list }}"
