---
# Installs smallstep cli and smallstep-CA if server: true
# Should account for RHEL, Debian/Ubuntu, and Alpine
# Installs root CA certificate for non server hosts

- name: Download step-cli package file
  ansible.builtin.get_url:
    url: "https://dl.smallstep.com/cli/docs-ca-install/latest/step-cli_amd64.{{ ansible_pkg_mgr }}"
    dest: "/tmp/step-cli_amd64.{{ ansible_pkg_mgr }}"
    mode: "755"
  vars:
    when: ansible_distribution != 'Alpine'
    ansible_pkg_mgr: "{{ 'deb' if ansible_distribution in ['Debian', 'Ubuntu'] else 'rpm' }}"

- name: Install step-cli deb
  ansible.builtin.apt:
    deb: /tmp/step-cli_amd64.deb
    state: present
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Install step-cli rpm
  community.general.apt_rpm:
    package: /tmp/step-cli_amd64.rpm
    state: present
  when: ansible_distribution in 'Redhat'

- name: Download step-ca deb
  ansible.builtin.get_url:
    url: "https://dl.smallstep.com/certificates/docs-ca-install/latest/step-ca_amd64.{{ ansible_pkg_mgr }}"
    dest: "/tmp/step-ca_amd64.{{ ansible_pkg_mgr }}"
    mode: "755"
  when: server | default(false) and ansible_distribution in ['Debian', 'Ubuntu', 'Redhat']

- name: Install step-ca package deb
  ansible.builtin.apt:
    deb: /tmp/step-ca_amd64.deb
    state: present
  when: server | default(false) and  ansible_distribution in ['Debian', 'Ubuntu']

- name: Install step-ca package rpm
  community.general.apt_rpm:
    package: /tmp/step-ca_amd64.rpm
    state: present
  when: server | default(false) and  ansible_distribution in 'Redhat'

- name: Install step-cli on Alpine
  community.general.apk:
    name: step-cli
    state: present
  when: ansible_distribution == 'Alpine'

- name: Install step-ca on Alpine
  community.general.apk:
    name: step-certificates
    state: present
  when: ansible_distribution == 'Alpine' and server | default(false)

- name: Set vault file
  ansible.builtin.include_vars:
    file: group_vars/smallstep.yml

- name: Run step-cli bootstrap command # noqa: command-instead-of-shell
  ansible.builtin.shell: "step ca bootstrap --ca-url {{ smallstep_ip }}:{{ smallstep_port }} --fingerprint {{ smallstep_root }}"
  when: not server | default(false)
  changed_when: true

- name: Install root CA certificate
  ansible.builtin.shell: "step certificate install $(step path)/certs/root_ca.crt"
  when: not server | default(false) and ansible_distribution != 'Alpine'
  changed_when: true
