---

- name: Create VM EVE-NG
  hosts: proxmox
  become: true
  remote_user: root
  vars:
    hostname: EVE-NG
    vmid: 665
    ip: '192.168.65.65/24'
    gw: '192.168.65.1'
    vlan: '65'
    ostemplate: "nas:iso/eve-ce-prod-6.2.0-3-regresshion-full.iso"
    description: "EVE-NG iso"
    storage: nvme
    disk: 'nvme:32'
    cpus: 8
    cores: 1
    memory: 16384
    features: null
    boot: false
    unprivileged: true
  roles:
    - proxmox_vm

- name: Wait for VM to be reachable/usable
  hosts: eve
  gather_facts: false
  tasks:
    - name: Wait for connection
      wait_for_connection:
        delay: 5
        timeout: 300

- name: Install ansible user
  hosts: eve
  remote_user: root
  gather_facts: true
  roles:
    - bootstrap