---

# Creates homer LXC using homer role
# https://github.com/bastienwirtz/homer

# Homer IP is hard coded as "homer" inventory role and below
# Would need to change vmid and ips for other containers

- name: Create LXC for homer
  hosts: proxmox
  become: true
  vars:
    hostname: homer
    vmid: 509
    ip: '192.168.55.9/24'
    gw: '192.168.55.1'
    vlan: '65'
    ostemplate: "local:vztmpl/alpine.tar.zst"
    storage: nvme
    disk: 'nvme:8'
    cpus: 1
    cores: 1
    memory: 1024
    boot: true
    description: 'Homer Dashboard made by ansible'
    features: null
    unprivileged: true
  roles:
    - proxmox

- name: Wait for VM to be reachable/usable
  hosts: homer
  gather_facts: false
  tasks:
    - name: Wait for connection
      wait_for_connection:
        delay: 5
        timeout: 300

- name: Bootstrap server
  hosts: homer
  remote_user: root
  gather_facts: true
  roles:
    - bootstrap

- name: Install homer
  hosts: homer
  remote_user: ansible
  gather_facts: true
  become: true
  roles:
    - homer

- name: Add syslog
  hosts: homer
  remote_user: ansible
  gather_facts: true
  become: true
  vars:
    syslog_server_ip: 192.168.55.50
  roles:
    - syslog_client
  tags: syslog
