---

- name: Create LXC for plex
  hosts: proxmox
  become: true
  vars:
    hostname: plexAnsible
    vmid: 692
    ip: '192.168.55.92/24'
    gw: '192.168.55.1'
    vlan: '65'
    ostemplate: "local:vztmpl/debian-11-standard_11.7-1_amd64.tar.zst"
    storage: nvme
    disk: 'nvme:8'
    cpus: 1
    cores: 4
    memory: 4096
    boot: true
    description: 'Plex host made by ansible'
    unprivileged: false
    features:
      - mount=cifs
      - nesting=1
  roles:
    - proxmox

- name: Add line to allow gpu passthrough
  hosts: proxmox
  vars:
    file_path: "/etc/pve/lxc/610.conf"
    line: "lxc.cgroup2.devices.allow: c 226:* rwm"
  roles:
    - role: add_line

- name: Add second line to allow gpu passthrough
  hosts: proxmox
  vars:
    file_path: "/etc/pve/lxc/610.conf"
    line: "lxc.mount.entry: /dev/dri dev/dri none bind,optional,create=dir"
  roles:
    - role: add_line

- name: Restart LXC
  hosts: proxmox
  vars:
    vmid: "610"
  roles:
    - role: restart_lxc

- name: Install ansible user
  hosts: plex
  gather_facts: false
  roles:
    - bootstrap

- name: Add syslog
  hosts: plex
  remote_user: ansible
  gather_facts: false
  become: true
  vars:
    syslog_server_ip: 192.168.55.50
  roles:
    - syslog_client
  tags: syslogs

- name: Install unzip
  hosts: plex
  remote_user: ansible
  gather_facts: false
  become: true
  vars:
    package_name: unzip
    package_state: present
  roles:
    - install

- name: Add nas to host
  hosts: plex
  remote_user: ansible
  gather_facts: false
  become: true
  vars_files:
    - group_vars/proxmox.yml
  roles:
    - add_nas

- name: Install plex and copy plex config
  hosts: plex
  remote_user: ansible
  gather_facts: false
  become: true
  roles:
    - plex
