--- 

- name: Create LXC for docker
  hosts: proxmox
  become: true
  vars:
    hostname: plexAnsible
    vmid: 510
    ip: '{"net0":"name=eth0,bridge=vmbr0,ip=192.168.55.10/24,gw=192.168.55.1"}'
    ostemplate: "local:vztmpl/debian-11-standard_11.7-1_amd64.tar.zst"
    storage: nvme
    disk: 'nvme:8'
    cpus: 1
    cores: 4
    memory: 4096
    boot: true
    description: 'Plex host made by ansible'
    unprivileged: false
    features:
      - mount=cifs
      - nesting=1
  roles:
    - proxmox

- name: Install ansible user
  hosts: plex
  gather_facts: false
  roles:
    - bootstrap

- name: Install unzip
  hosts: plex
  gather_facts: false
  vars:
    package_name: unzip
    package_state: present
  roles:
    - install

- name: Add nas to host
  hosts: plex
  become: true
  vars_files:
    - group_vars/proxmox.yml
  roles:
    - add_nas

- name: Install plex and copy plex config
  hosts: plex
  become: true
  roles:
    - plex

- name: Add syslog
  hosts: plex
  vars:
    syslog_server_ip: 192.168.55.50
  roles:
    - syslog_client
  tags: syslog