---

- name: Create LXC 71
  hosts: proxmox
  become: true
  remote_user: ansible
  vars:
    hostname: deb71
    vmid: 471
    ip: '{"net0":"name=eth0,bridge=vmbr0,ip=192.168.55.71/24,gw=192.168.55.1"}'
    ostemplate: "local:vztmpl/debian-11-standard_11.7-1_amd64.tar.zst"
    storage: nvme
    disk: 'nvme:8'
    cpus: 1
    cores: 1
    memory: 512
    features: null
    boot: false
    unprivileged: true
  roles:
    - proxmox
  tags: test

- name: Create LXC 72
  hosts: proxmox
  become: true
  remote_user: ansible
  vars:
    hostname: deb72
    vmid: 472
    ip: '{"net0":"name=eth0,bridge=vmbr0,ip=192.168.55.72/24,gw=192.168.55.1"}'
    ostemplate: "local:vztmpl/debian-11-standard_11.7-1_amd64.tar.zst"
    storage: nvme
    disk: 'nvme:8'
    cpus: 1
    cores: 1
    memory: 512
    onboot: false
    description: 'Test server made be ansible'
    features: null
    boot: false
    unprivileged: true
  roles:
    - proxmox
  tags: test

- name: Install ansible user
  hosts: containers
  remote_user: root
  gather_facts: false
  roles:
    - bootstrap
  tags: test

- name: Install tftp
  hosts: containers
  become: true
  remote_user: ansible
  roles:
    - tftp
  tags: test
