---

# General remove play
# usage:
# ansible-playbook remove.yml --extra-var "vimids=[<vimid>... ,<vimid2>]"

# or bash script:
# remove.sh <vimid1> [vimid2 ...]

- name: Delete LXC
  hosts: proxmox
  become: true
  roles:
    - remove
  vars:
    loop_list: "{{ vimids }}"
