---

- name: Install python3
  ansible.builtin.package:
    name: python3
    state: present

- name: Update
  community.general.apt:
    update-cache: true

- name: Create website var directory
  ansible.builtin.file:
    path: /var/website/
    state: directory
    mode: '0755'

- name: Copy html file to server
  ansible.builtin.copy:
    src: /home/greg/projects/ansible_proxmox/roles/simple_website/files/index.html
    dest: /var/website
    mode: '0644'

- name: Copy css file to server
  ansible.builtin.copy:
    src: /home/greg/projects/ansible_proxmox/roles/simple_website/files/form.css
    dest: /var/website
    mode: '0644'

- name: Create Python script to start HTTP server
  ansible.builtin.copy:
    content: |
      #!/usr/bin/env python3
      import http.server
      import socketserver
      import os

      PORT = 80
      DIRECTORY = "/var/website"

      os.chdir(DIRECTORY)

      handler = http.server.SimpleHTTPRequestHandler
      handler.directory = DIRECTORY

      with socketserver.TCPServer(("", PORT), handler) as httpd:
          print(f"Serving at port {PORT}")
          httpd.serve_forever()
    dest: /var/website/start_server.py
    mode: '0755'

- name: Start http server
  ansible.builtin.shell: nohup python3 /var/website/start_server.py > /dev/null 2>&1 &
  args:
    executable: /bin/bash
  changed_when: true
