---
# Installs tftp server
# Tftp Directory is in /var/tftpboot
# Adds an empty test file for easier testing

- name: Install tftpd-hpa
  tags: tftp
  ansible.builtin.package:
    name: tftp-hpa

- name: Start tftpd-hpa
  ansible.builtin.service:
    name: in.tftpd
    state: started

- name: Add tftpd-hpa to default runlevel
  ansible.builtin.command:
    cmd: rc-update add in.tftpd default
  changed_when: true

- name: Start tftpd-hpa
  ansible.builtin.service:
    name: in.tftpd
    state: started

- name: Create test file
  ansible.builtin.file:
    path: /var/tftpboot/test
    state: touch
    owner: root
    group: root
    mode: '777'
