---
# Installs homer using template file
# Has folder for personal icons
# Can update template file as needed
# Uses generic config file to add to systemctl

- name: Install unzip
  ansible.builtin.package:
    name: unzip

- name: Get homer release zip
  ansible.builtin.get_url:
    url: https://github.com/bastienwirtz/homer/releases/latest/download/homer.zip
    dest: /tmp/homer.zip
    owner: ansible
    group: ansible
    mode: '0644'

- name: Make homer dir
  ansible.builtin.file:
    path: /opt/homer
    state: directory
    owner: ansible
    group: ansible
    mode: '0644'

- name: Unzip homer.zip
  ansible.builtin.unarchive:
    remote_src: true
    src: /tmp/homer.zip
    dest: /opt/homer
  changed_when: true

- name: Copy config file
  ansible.builtin.template:
    src: ~/projects/ansible_proxmox/roles/homer/templates/config.j2
    dest: /opt/homer/assets/config.yml
    owner: ansible
    group: ansible
    mode: '0644'
  changed_when: true

- name: Copy icons
  ansible.builtin.copy:
    src: ~/projects/ansible_proxmox/roles/homer/files/
    dest: /opt/homer/assets/icons
    owner: ansible
    group: ansible
    mode: '0644'
  changed_when: true

- name: Install python3
  ansible.builtin.package:
    name: python3

- name: Copy config file
  ansible.builtin.template:
    src: ~/projects/ansible_proxmox/roles/homer/templates/service.j2
    dest: /etc/systemd/system/homer.service
    owner: root
    group: root
    mode: '0644'
  changed_when: true
  when: ansible_distribution != "Alpine"

- name: Copy config file alpine
  ansible.builtin.template:
    src: ~/projects/ansible_proxmox/roles/homer/templates/openrc.j2
    dest: /etc/init.d/homer
    owner: root
    group: root
    mode: '0755'
  changed_when: true
  when: ansible_distribution == "Alpine"

- name: Start homer
  ansible.builtin.systemd_service:
    name: homer
    state: started
    enabled: true
  changed_when: true
  when: ansible_distribution != "Alpine"

- name: Start homer alpine
  ansible.builtin.service:
    name: homer
    state: started
    enabled: true
  become: true
  when: ansible_distribution == "Alpine"
